### ISSUE TITLE
DB클래스 pk증가 메서드

### ISSUE THREAD

**Issue by SiJun-Yoo** [SiJun-Yoo/Event-Cafe-Cloud#25]
- [x] DB클래스의 pk증가 메서드를 증가시켜주는 key값을 지정할 수 있도록 수정
- [x] 초기에 pk의 값을 정해주는 로직 수정
* 각 Collection의 PK값을 일괄적으로 ${Collection이름}_id로 수정하는게 어떨까요

**Comment by aichyu312** [comment]
${Collection이름}_id 확인했습니다 . 규칙이나 통일성은 천천히 지켜서 숙달되면 좋을것 같습니다.
